### ISSUE TITLE
NOT ABLE TO INSTALL PLUGIN

### ISSUE THREAD

**Issue by anuvak26** [apache/cordova-plugin-geolocation#116]
When I am trying to install the plugin I am getting this error previously it was working fine :

```
Installing "cordova-plugin-geolocation" for android
Failed to install 'cordova-plugin-geolocation': Error: ENOENT: no such file or directory, open '/var/www/html/WHATSUPLIFE/test/platforms/android/AndroidManifest.xml'
    at Object.openSync (fs.js:434:3)
    at Object.readFileSync (fs.js:339:35)
    at Object.parseElementtreeSync (/var/www/html/WHATSUPLIFE/test/platforms/android/cordova/node_modules/cordova-common/src/util/xml-helpers.js:180:27)
    at new AndroidManifest (/var/www/html/WHATSUPLIFE/test/platforms/android/cordova/lib/AndroidManifest.js:29:20)
    at AndroidProject.getPackageName (/var/www/html/WHATSUPLIFE/test/platforms/android/cordova/lib/AndroidProject.js:99:12)
    at Api.addPlugin (/var/www/html/WHATSUPLIFE/test/platforms/android/cordova/Api.js:223:57)
    at handleInstall (/home/webdior/.nvm/versions/node/v10.9.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:594:10)
    at /home/webdior/.nvm/versions/node/v10.9.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:357:28
    at _fulfilled (/home/webdior/.nvm/versions/node/v10.9.0/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at /home/webdior/.nvm/versions/node/v10.9.0/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30
(node:14997) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/var/www/html/WHATSUPLIFE/test/platforms/android/AndroidManifest.xml'
    at Object.openSync (fs.js:434:3)
    at Object.readFileSync (fs.js:339:35)
    at Object.parseElementtreeSync (/var/www/html/WHATSUPLIFE/test/platforms/android/cordova/node_modules/cordova-common/src/util/xml-helpers.js:180:27)
    at new AndroidManifest (/var/www/html/WHATSUPLIFE/test/platforms/android/cordova/lib/AndroidManifest.js:29:20)
    at AndroidProject.getPackageName (/var/www/html/WHATSUPLIFE/test/platforms/android/cordova/lib/AndroidProject.js:99:12)
    at Api.addPlugin (/var/www/html/WHATSUPLIFE/test/platforms/android/cordova/Api.js:223:57)
    at handleInstall (/home/webdior/.nvm/versions/node/v10.9.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:594:10)
    at /home/webdior/.nvm/versions/node/v10.9.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:357:28
    at _fulfilled (/home/webdior/.nvm/versions/node/v10.9.0/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at /home/webdior/.nvm/versions/node/v10.9.0/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30
(node:14997) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14997) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any help is appreciated.

**Comment by anuvak26** [comment]
@janpio 
Ionic:

   ionic (Ionic CLI)  : 4.1.1 (/home/webdior/.nvm/versions/node/v10.9.0/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.3, (and 15 other plugins)

System:

   NodeJS : v10.9.0 (/home/webdior/.nvm/versions/node/v10.9.0/bin/node)
   npm    : 6.2.0
   OS     : Linux 4.15

**Comment by janpio** [comment]
> Cordova Platforms : android 7.0.0

Your Cordova tooling seems to be out of date, which might be causing all kinds of problems. 
You can read about how to figure out the current Cordova versions and how to update CLI, platforms and plugins here: https://ionic.zone/cordova/update

Unrelated, but `@ionic/app-scripts : 3.1.10` is also outdated.

You also didn't answer my question what plugin version you are actually trying to install.

**Comment by anuvak26** [comment]
I am trying to install the plugin using the command that is specified in ionic framework documentation.
i.e  ionic cordova plugin add cordova-plugin-geolocation --variable GEOLOCATION_USAGE_DESCRIPTION="To locate you"

**Comment by anuvak26** [comment]
Updated the Cordova android platform to 7.1.1 and @ionic/app-scripts still not working.

**Comment by anuvak26** [comment]
@janpio  this not able to find AndroidManifest.xml is happening with other plugins so if I think that it is ionic plugins issue then I am sorry but I am wrong. It starts happening after the I updated my ionic CLI to 4.

**Comment by janpio** [comment]
No, one of the plugins you are using is probably not ready for Cordova Android 7.x which moved some stuff around. Ionic CLI doesn't have any effect here by the way, it is probably unrelated and just triggered by you re-installing stuff.

Please create a new project (`ionic start` in your case) and install this plugin here only. If it works, this is not an issue of this plugin but your individual project. Find the difference, fix it.

**Comment by anuvak26** [comment]
These Plugins were working perfectly..... I have not added any new plugin in the list. 

Tried with the new project still not working

**Comment by janpio** [comment]
Well, works for me just fine:

```
C:\Projects\experiments
λ cordova create geolocationProof
Creating a new cordova project.

C:\Projects\experiments
λ cd geolocationProof\

C:\Projects\experiments\geolocationProof  (helloworld@1.0.0)
λ cordova platform add android@7.1.1
Using cordova-fetch for cordova-android@7.1.1
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: io.cordova.hellocordova
        Name: HelloCordova
        Activity: MainActivity
        Android target: android-27
Android project created with cordova-android@7.1.1
Android Studio project detected
Android Studio project detected
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.

Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
--save flag or autosave detected
Saving android@~7.1.1 into config.xml file ...

C:\Projects\experiments\geolocationProof  (helloworld@1.0.0)
λ cordova plugin add cordova-plugin-geolocation
Installing "cordova-plugin-geolocation" for android
Android Studio project detected
Adding cordova-plugin-geolocation to package.json
Saved plugin info for "cordova-plugin-geolocation" to config.xml
```

**Comment by janpio** [comment]
Same result for creating the project with Ionic CLI by the way:

```
C:\Projects\experiments
λ ionic start geolocationProof2

Let's pick the perfect starter template!

Starter templates are ready-to-go Ionic apps that come packed with everything you need to build your app. To bypass this
prompt next time, supply template, the second argument to ionic start.

? Starter template: blank
√ Preparing directory .\geolocationProof2 - done!
√ Downloading and extracting blank starter - done!
? Integrate your new app with Cordova to target native iOS and Android? No

Installing dependencies may take several minutes.

     *   IONIC  DEVAPP   *

 Speed up development with the Ionic DevApp, our fast, on-device testing mobile app

  -     Test on iOS and Android without Native SDKs
  -     LiveReload for instant style and JS updates

 -->    Install DevApp: https://bit.ly/ionic-dev-app    <--

────────────────────────────────────────────────────────────

> npm i

> node-sass@4.9.0 install C:\Projects\experiments\geolocationProof2\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\Jan\AppData\Roaming\npm-cache\node-sass\4.9.0\win32-x64-64_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall C:\Projects\experiments\geolocationProof2\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js


> node-sass@4.9.0 postinstall C:\Projects\experiments\geolocationProof2\node_modules\node-sass
> node scripts/build.js

Binary found at C:\Projects\experiments\geolocationProof2\node_modules\node-sass\vendor\win32-x64-64\binding.node
Testing binary
Binary is fine
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 738 packages from 660 contributors and audited 6209 packages in 58.329s
found 0 vulnerabilities

> git init
Initialized empty Git repository in C:/Projects/experiments/geolocationProof2/.git/

     *   IONIC  PRO   *

 Supercharge your Ionic development with the Ionic Pro SDK

  -     Track runtime errors in real-time, back to your original TypeScript
  -    Push remote updates and skip the app store queue

 Learn more about Ionic Pro: https://ionicframework.com/pro

────────────────────────────────────────────────────────────

? Install the free Ionic Pro SDK and connect your app? No
> git add -A
warning: LF will be replaced by CRLF in .editorconfig.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in .gitignore.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in ionic.config.json.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in package-lock.json.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in package.json.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in src/app/app.component.ts.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in src/app/app.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in src/app/app.module.ts.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in src/app/app.scss.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in src/app/main.ts.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in src/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in src/manifest.json.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in src/pages/home/home.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in src/pages/home/home.scss.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in src/pages/home/home.ts.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in src/service-worker.js.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in src/theme/variables.scss.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in tsconfig.json.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in tslint.json.
The file will have its original line endings in your working directory.
> git commit -m "Initial commit" --no-gpg-sign
[master (root-commit) c29e72c] Initial commit
 21 files changed, 7188 insertions(+)
 create mode 100644 .editorconfig
 create mode 100644 .gitignore
 create mode 100644 ionic.config.json
 create mode 100644 package-lock.json
 create mode 100644 package.json
 create mode 100644 src/app/app.component.ts
 create mode 100644 src/app/app.html
 create mode 100644 src/app/app.module.ts
 create mode 100644 src/app/app.scss
 create mode 100644 src/app/main.ts
 create mode 100644 src/assets/icon/favicon.ico
 create mode 100644 src/assets/imgs/logo.png
 create mode 100644 src/index.html
 create mode 100644 src/manifest.json
 create mode 100644 src/pages/home/home.html
 create mode 100644 src/pages/home/home.scss
 create mode 100644 src/pages/home/home.ts
 create mode 100644 src/service-worker.js
 create mode 100644 src/theme/variables.scss
 create mode 100644 tsconfig.json
 create mode 100644 tslint.json

[INFO] Next Steps:

       - Go to your newly created project: cd .\geolocationProof2
       - Get Ionic DevApp for easy device testing: https://bit.ly/ionic-dev-app

C:\Projects\experiments
λ cd geolocationProof2

C:\Projects\experiments\geolocationProof2 (master -> origin)
λ ionic cordova platform add android@7.1.1
> ionic integrations enable cordova
[INFO] Downloading integration cordova
[INFO] Copying integrations files to project
CREATE config.xml
CREATE resources
CREATE resources\android
CREATE resources\icon.png
CREATE resources\ios
CREATE resources\README.md
CREATE resources\splash.png
CREATE resources\android\icon
CREATE resources\android\splash
CREATE resources\ios\icon
CREATE resources\ios\splash
CREATE resources\android\icon\drawable-hdpi-icon.png
CREATE resources\android\icon\drawable-ldpi-icon.png
CREATE resources\android\icon\drawable-mdpi-icon.png
CREATE resources\android\icon\drawable-xhdpi-icon.png
CREATE resources\android\icon\drawable-xxhdpi-icon.png
CREATE resources\android\icon\drawable-xxxhdpi-icon.png
CREATE resources\android\splash\drawable-land-hdpi-screen.png
CREATE resources\android\splash\drawable-land-ldpi-screen.png
CREATE resources\android\splash\drawable-land-mdpi-screen.png
CREATE resources\android\splash\drawable-land-xhdpi-screen.png
CREATE resources\android\splash\drawable-land-xxhdpi-screen.png
CREATE resources\android\splash\drawable-land-xxxhdpi-screen.png
CREATE resources\android\splash\drawable-port-hdpi-screen.png
CREATE resources\android\splash\drawable-port-ldpi-screen.png
CREATE resources\android\splash\drawable-port-mdpi-screen.png
CREATE resources\android\splash\drawable-port-xhdpi-screen.png
CREATE resources\android\splash\drawable-port-xxhdpi-screen.png
CREATE resources\android\splash\drawable-port-xxxhdpi-screen.png
CREATE resources\ios\icon\icon-1024.png
CREATE resources\ios\icon\icon-40.png
CREATE resources\ios\icon\icon-40@2x.png
CREATE resources\ios\icon\icon-40@3x.png
CREATE resources\ios\icon\icon-50.png
CREATE resources\ios\icon\icon-50@2x.png
CREATE resources\ios\icon\icon-60.png
CREATE resources\ios\icon\icon-60@2x.png
CREATE resources\ios\icon\icon-60@3x.png
CREATE resources\ios\icon\icon-72.png
CREATE resources\ios\icon\icon-72@2x.png
CREATE resources\ios\icon\icon-76.png
CREATE resources\ios\icon\icon-76@2x.png
CREATE resources\ios\icon\icon-83.5@2x.png
CREATE resources\ios\icon\icon-small.png
CREATE resources\ios\icon\icon-small@2x.png
CREATE resources\ios\icon\icon-small@3x.png
CREATE resources\ios\icon\icon.png
CREATE resources\ios\icon\icon@2x.png
CREATE resources\ios\splash\Default-568h@2x~iphone.png
CREATE resources\ios\splash\Default-667h.png
CREATE resources\ios\splash\Default-736h.png
CREATE resources\ios\splash\Default-Landscape-736h.png
CREATE resources\ios\splash\Default-Landscape@2x~ipad.png
CREATE resources\ios\splash\Default-Landscape@~ipadpro.png
CREATE resources\ios\splash\Default-Landscape~ipad.png
CREATE resources\ios\splash\Default-Portrait@2x~ipad.png
CREATE resources\ios\splash\Default-Portrait@~ipadpro.png
CREATE resources\ios\splash\Default-Portrait~ipad.png
CREATE resources\ios\splash\Default@2x~iphone.png
CREATE resources\ios\splash\Default@2x~universal~anyany.png
CREATE resources\ios\splash\Default~iphone.png
[OK] Integration cordova added!
√ Creating .\www directory for you - done!
> cordova platform add android@7.1.1 --save
Using cordova-fetch for cordova-android@7.1.1
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: io.ionic.starter
        Name: MyApp
        Activity: MainActivity
        Android target: android-27
Android project created with cordova-android@7.1.1
Android Studio project detected
Android Studio project detected
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.

Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
Discovered plugin "cordova-plugin-statusbar" in config.xml. Adding it to the project
Installing "cordova-plugin-statusbar" for android
Adding cordova-plugin-statusbar to package.json
Saved plugin info for "cordova-plugin-statusbar" to config.xml
Discovered plugin "cordova-plugin-device" in config.xml. Adding it to the project
Installing "cordova-plugin-device" for android
Adding cordova-plugin-device to package.json
Saved plugin info for "cordova-plugin-device" to config.xml
Discovered plugin "cordova-plugin-splashscreen" in config.xml. Adding it to the project
Installing "cordova-plugin-splashscreen" for android
Adding cordova-plugin-splashscreen to package.json
Saved plugin info for "cordova-plugin-splashscreen" to config.xml
Discovered plugin "cordova-plugin-ionic-webview" in config.xml. Adding it to the project
Installing "cordova-plugin-ionic-webview" for android
Subproject Path: CordovaLib
Subproject Path: app
Adding cordova-plugin-ionic-webview to package.json
Saved plugin info for "cordova-plugin-ionic-webview" to config.xml
Discovered plugin "cordova-plugin-ionic-keyboard" in config.xml. Adding it to the project
Installing "cordova-plugin-ionic-keyboard" for android
Adding cordova-plugin-ionic-keyboard to package.json
Saved plugin info for "cordova-plugin-ionic-keyboard" to config.xml
--save flag or autosave detected
Saving android@~7.1.1 into config.xml file ...

C:\Projects\experiments\geolocationProof2 (master -> origin)
λ ionic cordova plugin add cordova-plugin-geolocation
> cordova plugin add cordova-plugin-geolocation --save
Installing "cordova-plugin-geolocation" for android
Android Studio project detected
Adding cordova-plugin-geolocation to package.json
Saved plugin info for "cordova-plugin-geolocation" to config.xml
```

**Comment by anuvak26** [comment]
@janpio  I don't have any personal grudges with the ionic or ionic team .. I am facing this issue from past one week and tried everything that you said. Still, Thank you for rude and not so helpful nature.

**Comment by janpio** [comment]
Are you aware that you are posting in the Cordova plugin's issue tracker here? Nothing here is about Ionic. You are using Ionic, which just uses Cordova in the background. To adapt my response to your environment, I even ran the command with Ionic CLI just to make sure there is no strange effect that makes it fail there. 

If you think this is an Ionic issue, you should ask over at Ionic's repository or forum.
