### ISSUE TITLE
Unhandled Promise rejection: Cannot read property '_privateInitialize' of undefined ;

### ISSUE THREAD

**Issue by Ghayyas** [apache/cordova-plugin-geolocation#137]
Why is this happens whats the issue?

```
Unhandled Promise rejection: Cannot read property '_privateInitialize' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property '_privateInitialize' of undefined
    at Map.<anonymous> (Map.js:1415)
    at commandQueueExecutor.js:63
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at o (polyfills.js:3) TypeError: Cannot read property '_privateInitialize' of undefined
    at Map.<anonymous> (http://localhost:8080/plugins/cordova-plugin-googlemaps/www/Map.js:1415:12)
    at http://localhost:8080/plugins/cordova-plugin-googlemaps/www/commandQueueExecutor.js:63:21
    at t.invoke (http://localhost:8080/build/polyfills.js:3:14976)
    at r.run (http://localhost:8080/build/polyfills.js:3:10143)
    at http://localhost:8080/build/polyfills.js:3:20242
    at t.invokeTask (http://localhost:8080/build/polyfills.js:3:15660)
    at r.runTask (http://localhost:8080/build/polyfills.js:3:10834)
    at o (http://localhost:8080/build/polyfills.js:3:7894)
n.onUnhandledError @ polyfills.js:3
r @ polyfills.js:3
(anonymous) @ polyfills.js:3
n.microtaskDrainDone @ polyfills.js:3
o @ polyfills.js:3
Promise.then (async)
r @ polyfills.js:3
t.scheduleTask @ polyfills.js:3
r.scheduleTask @ polyfills.js:3
r.scheduleMicroTask @ polyfills.js:3
f @ polyfills.js:3
t.then @ polyfills.js:3
nextTick @ Common.js:6
commandQueue.push.args @ commandQueueExecutor.js:62
callbackFromNative @ cordova.js:291
(anonymous) @ VM312:1
```

**Comment by janpio** [comment]
```
    at Map.<anonymous> (http://localhost:8080/plugins/cordova-plugin-googlemaps/www/Map.js:1415:12)
    at http://localhost:8080/plugins/cordova-plugin-googlemaps/www/commandQueueExecutor.js:63:21
```

Wrong plugin repository?

**Comment by Ghayyas** [comment]
Wrong Plugin? how do I remove this error and make the code to work?

**Comment by janpio** [comment]
Ask at the repository of `cordova-plugin-googlemaps`, not `cordova-plugin-geolocation`.

**Comment by Ghayyas** [comment]
You mean Issue is from Cordova google maps?

**Comment by Ghayyas** [comment]
Actually it didn't detect the geolocation. When I see the console it throws this error..
